language: go
go:
  - master
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/tools/godep
script:
  - go install
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o dnswait-linux-amd64 .
  - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -a -installsuffix cgo -o dnswait-darwin-amd64 .
  - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -a -installsuffix cgo -o dnswait-windows-amd64.exe .
  - CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -a -installsuffix cgo -o dnswait-windows-386.exe .
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - dnswait-linux-amd64
    - dnswait-darwin-amd64
    - dnswait-windows-amd64
    - dnswait-windows-386
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    on_success: never
    on_failure: always
